language: r
sudo: false
cache: packages
  
r_packages:
 - covr
 
warnings_are_errors: false

cran: http://cran.rstudio.com

script: ./travis-tool.sh run_tests

after_success:
  - Rscript -e 'covr::coveralls()'

after_failure:
  - ./travis-tool.sh dump_logs

